using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.Extensions.AppccelerateEventBroker: AppccelerateEventBroker Extension for Ninject")]
[assembly: AssemblyCompanyAttribute("Ninject Project Contributors")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2009-2014 Ninject Project Contributors")]
[assembly: AssemblyVersionAttribute("2.1.0.6")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

